### ISSUE TITLE
Warnings for masking `export_as_txt`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rlistings#98] opened 2023-03-01 15:15 UTC
```
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘rlistings::export_as_txt’ by ‘rtables::export_as_txt’ when loading ‘scda.test’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘rlistings::export_as_txt’ by ‘rtables::export_as_txt’ when loading ‘scda.test’
** testing if installed package can be loaded from final location
Warning: replacing previous import ‘rlistings::export_as_txt’ by ‘rtables::export_as_txt’ when loading ‘scda.test’
** testing if installed package keeps a record of temporary installation path
* DONE (scda.test)
```
Maybe, as it is just a temporary solution before the creation of the generics, we could rename it `export_rlisting_as_txt`

**Comment by shajoezhu** [comment] 2023-03-01 23:01
currently in citril, @clarkliming have been calling these explicitly as "rlistings::export_as_txt’ by ‘rtables::export_as_txt’", it's a warning for now. let's refactor this very soon after the release

**Comment by clarkliming** [comment] 2023-03-02 01:53
yes this is also user facing issue. best if it can be a generic in formatters.

**Comment by gmbecker** [comment] 2023-03-13 23:24
@clarkliming @shajoezhu are we shipping to CRAN as is with respect to this? 

Its an easy change to the name of the function since it hasn't been in a public facing release yet, so we could chnage the name, e.g., to `listing_to_text` or `export_listing_as_txt` as Davide suggests above.

Any name we give something hardcoded to only work on listings is going to be temporary anyway, once the logic is correctly generic-ified and pushed down into formatters, which I believe we all agree should and will happen.

**Comment by shajoezhu** [comment] 2023-03-14 00:11
hi @gmbecker , yes, we are skipping this. we will do the export_as_txt in the next few weeks.

**Comment by gmbecker** [comment] 2023-04-13 00:08
Closing this as duplicate of #96

**Closed by gmbecker** 2023-04-13 00:08 UTC
Labels: bug, sme, discussion
