### ISSUE TITLE
Possible bug: export_as_pdf() pagination carries over last value in "display" columns to next page

### ISSUE THREAD

**Issue by kyleireton** [insightsengineering/rlistings#233] opened 2024-11-21 01:07 UTC
I suspect this is a bug, but I can't figure it out so would be grateful for any insight:

When using the "export_as_pdf()" function with pagination = TRUE, if the first row of a new page in a disp_cols() variable is blank, the listing instead carries over the last printed value from that variable in the first row. Just to be clear, that's problematic in our usage because it makes it appear there is data occurring where it should not be. 

I confirmed this occurs within pagination of key_col() variables. In our case, when grouping by Subject ID as a key_col(), the data is carried over on the first row only when paginating within that Subject ID. When a new Subject ID begins on the first row of a new page, the last printed display_col() value is *not* carried over even if the first row is blank (which is the behavior we wish to see for all pages).

I tried not defining any key_col(), but I still see display_col() values carried over to fill blank first rows after pagination.

**Comment by kyleireton** [comment] 2024-11-21 01:12
For a bit more context, I confirmed that the carryover of data only occurs in the case of pagination with export_as_pdf(). When creating the listing itself by as_listing(), blank cells in rows are displayed as intended.

**Comment by kyleireton** [comment] 2024-11-21 04:47
It appears the issue is resolved by replacing absolute empty values "" with a real space " ". I tried it first with a period ".", and that fixed it as well.

**Comment by shajoezhu** [comment] 2024-11-21 15:24
> It appears the issue is resolved by replacing absolute empty values "" with a real space " ". I tried it first with a period ".", and that fixed it as well.

Thanks @kyleireton !

closing this issue, as already resolved by user

**Closed by shajoezhu** 2024-11-21 15:24 UTC
Labels: bug

**Comment by Melkiades** [comment] 2024-11-21 15:52
> It appears the issue is resolved by replacing absolute empty values "" with a real space " ". I tried it first with a period ".", and that fixed it as well.

Good fix! Thanks 👍

**Comment by gmbecker** [comment] 2026-04-21 01:30
If I understand correctly, this is by design, as without it if you look at the page in isolation you will have no way of knowing what patient the data at the top of the page corresponds to. 

`formatters` based pagination, as used across both `rtables` and `rlistings`, is intended specifically to repeat all context necessary to understand the the first new row on the table.
